#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0

#bspc config normal_border_color "#343434"
#bspc config active_border_color "#212121"

bspc config window_gap          12
bspc config border_radius       10
bspc config top_padding         45
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^3' follow=on
bspc rule -a spotify desktop='^5' follow=on
bspc rule -a discord desktop='^4' follow=on

# Startup
pulseaudio -D &
xsetroot -cursor_name left_ptr
picom --experimental-backends --backend glx -b &
dunst &
nitrogen --restore &
$HOME/.local/bin/eww open bar -c $HOME/.config/eww


